# Generated by Django 2.0.2 on 2018-02-17 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_fi', models.TextField(null=True)),
                ('name_en', models.TextField(null=True)),
                ('notes', models.TextField()),
                ('notes_fi', models.TextField(null=True)),
                ('notes_en', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_fi', models.TextField(null=True)),
                ('name_en', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.FoodCategory'),
        ),
    ]
