# Generated by Django 2.0.2 on 2018-02-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='name_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='name_fi',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='notes_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='notes_fi',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='name_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='name_fi',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
