# Generated by Django 2.0.2 on 2018-02-18 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20180218_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('name_fi', models.TextField(blank=True, default='', null=True)),
                ('name_en', models.TextField(blank=True, default='', null=True)),
                ('level', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.FoodClassification'),
        ),
    ]
